### ISSUE TITLE
Deprication warning

### ISSUE THREAD

**Issue by opieters** [dwengovzw/Dwengo-library#14]
Hi 

When using the board with a recent version of Arduino IDE (1.8.5) I get the following warning:

```
Warning: platform.txt from core 'Dwenguino Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
```

This should be fixed to ensue operation with future versions of Arduino IDE.

**Comment by JelleRoets** [comment]
We recently released a new version of the Dwenguino package: v2.2.1. This should fix all existing compiler and platform warnings.
